services:
  - type: web
    name: kryros-backend
    env: node
    region: oregon
    buildCommand: cd Backend && npm install && npx prisma generate
    startCommand: cd Backend && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://kryros.onrender.com,https://kryrosadminpanel.onrender.com
      - key: FRONTEND_URL
        value: https://kryros.onrender.com

  - type: web
    name: kryros-user-ui
    env: node
    region: oregon
    buildCommand: cd Frontend/User-UI && npm install && npm run build
    startCommand: cd Frontend/User-UI && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://kryrosbackend.onrender.com/api

  - type: web
    name: kryros-admin
    env: node
    region: oregon
    buildCommand: cd Frontend/Admi-Panel && npm install && npm run build
    startCommand: cd Frontend/Admi-Panel && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://kryrosbackend.onrender.com/api
